modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

[[mods]]
modId="gbr"
version="1.3.3.7"
displayName="Gun Battle Royale"
logoFile="gbr.png"
authors="Moon404"
description='''
A Battle Royale Mod.
Based on MrCrayfish's Gun Mod.
'''

[[dependencies.gbr]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gbr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gbr]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.3,)"
    ordering="NONE"
    side="BOTH"